### ISSUE TITLE
Can i deploy in ubuntu using 0.0.0.0 not localhost and use transcription feature?

### ISSUE THREAD

**Issue by johnfelipe** [CouncilDataProject/cookiecutter-cdp-deployment#109]
Can i deploy in ubuntu using 0.0.0.0 not localthos and use transcription feature?

**Comment by evamaxfield** [comment]
I am very confused as to what you are asking for.

If you could provide more context I would be happy to answer.

**Comment by johnfelipe** [comment]
![SNAG-0089](https://user-images.githubusercontent.com/428820/183078310-429e6a60-13a1-4c23-ac9a-f1e2b77360fe.png)

i want to test this feature in local enviroment

**Comment by evamaxfield** [comment]
You can make your own dev infrastructure but none of it is local. We don't have any local deployment docs and experience. If you wanted to give it a try, and write notes as to how to do it, happy to accept those as a docs PR. But it's nothing we are currently looking at doing.

**Comment by evamaxfield** [comment]
Also note: regardless of "local" deployment or "standard GitHub + Google Cloud" deployment, the transcription part of CDP is simply sending audio to Google Speech-to-Text so at the bare minimum you will need the Google Storage + Google Speech-to-Text.

If you are interested in setting up a quick dev infrastructure: https://github.com/CouncilDataProject/cdp-backend/tree/main/dev-infrastructure

**Comment by johnfelipe** [comment]
ok then about transcription is with GCP?
That transcription is automatically?
only source of transcription is a video?

**Comment by evamaxfield** [comment]
> ok then about transcription is with GCP?
yes
> That transcription is automatically?
yes
> only source of transcription is a video?
yes. currently. issue for "allowing processing only audio" here: https://github.com/CouncilDataProject/cdp-backend/issues/87
