### ISSUE TITLE
[Instance]: Pittsburgh, PA

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cookiecutter-cdp-deployment#123]
### Municipality Name

Pittsburgh

### Municipality Timezone

America/New_York

### Governing Body Type

city council

### Maintainer GitHub Name

dphoria

### Legistar Client Id

pittsburghpa

### Municipality Slug

pittsburgh-pa

### Firestore Region

us-east4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dphoria** [comment]
Crap. I entered the wrong Legistar client ID. it's apparently [`pittsburgh`](https://pittsburgh.legistar.com/Calendar.aspx), not `pittsburghpa`. What's the best way to fix that? Just close this issue and open a new one?

**Comment by evamaxfield** [comment]
Yea just close and reopen
