### ISSUE TITLE
[Instance]: Pittsburgh, PA

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cookiecutter-cdp-deployment#124]
### Municipality Name

Pittsburgh

### Municipality Timezone

America/New_York

### Governing Body Type

city council

### Maintainer GitHub Name

dphoria

### Legistar Client Id

pittsburgh

### Municipality Slug

pittsburgh-pa

### Firestore Region

us-east4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dphoria** [comment]
I will pay for this instance.

**Comment by dphoria** [comment]
I thought I'd try out the 'steps for the internal team' myself, but I have no idea where `get_cdp_infrastructure_stack` so I'm gonna leave it alone. :sweat_smile:  Have a great weekend.

**Comment by evamaxfield** [comment]
`get_cdp_infrastructure_stack` is installed when you install cdp-backend. It's just the new method we use for shipping infrastructure. We literally ship a bunch of bash and JSON files to unpack and then run.

And lol don't worry about paying. We will pay

**Comment by evamaxfield** [comment]
I'll deploy this in later morning / early afternoon

**Comment by evamaxfield** [comment]
Deployment Status - Complete

GitHub: https://github.com/CouncilDataProject/pittsburgh-pa
Webpage: https://councildataproject.org/pittsburgh-pa
Initial Backfill: https://github.com/CouncilDataProject/pittsburgh-pa/actions/runs/3073910412/jobs/4966337427

**Comment by dphoria** [comment]
> Deployment Status - Complete
> 
> GitHub: https://github.com/CouncilDataProject/pittsburgh-pa Webpage: https://councildataproject.org/pittsburgh-pa Initial Backfill: https://github.com/CouncilDataProject/pittsburgh-pa/actions/runs/3073910412/jobs/4966337427

🙏
