### ISSUE TITLE
Break the deployment cookiecutter

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#17]
As one of the main goals of the project is to be as easily deployable as possible, we need to continuous "stress test" our deployment process. Any and all comments on what is good, bad, confusing, or even not-helpful to documenting and actually carrying out a deployment process should be placed as comments on this GitHub Issue.

In short, you should start at one-of (your choice):
1. [CDP Home](https://councildataproject.github.io/)
2. [cookiecutter repo (this repo)](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment)
3. [cdp-backend repo](https://github.com/CouncilDataProject/cdp-backend)

And attempt to fully create your own repo with a `get_events` function and has all GitHub Actions succeed.

Do not be afraid to be critical and / or nitpicky. This is exactly what we want.

**Comment by JacksonMaxfield** [comment]
Move `Usage` section of cookiecutter repo higher to the top of the README.

**Comment by JacksonMaxfield** [comment]
Add comments in README documenting each parameter to the cookiecutter.

i.e. what is a "municipality_slug", why is it different from "python_municipality_slug"?

This may be an argument for removing those from the template and computing them before injection each time? Unless cookiecutter has a way of hiding parameters?

**Comment by JacksonMaxfield** [comment]
The cookiecutter process simply ended, there was no indication as to where to go next. (`cd king-county`)

**Comment by JacksonMaxfield** [comment]
I started out on `cdp-backend` repo, and I went to the website first then scrolled down to contributing. Make it more obvious both on the website and in all repos what a "deploy" / "cookiecutter" is and how to create your own instance....

**Comment by isometimescode** [comment]
Add a non-technical overview of how to use the cookiecutter after deployment/installation; basically after running some commands in the terminal, how do I tell if it worked or not?

**Comment by isometimescode** [comment]
I don't have specific errors to add right now, but it would be helpful to have a list of solutions to common errors in the cookiecutter README.

**Comment by JacksonMaxfield** [comment]
There are directions in the created / generated README but no obvious way of knowing where to see those directions. Again, there should be some post generate repo message that says go the README.

**Comment by JacksonMaxfield** [comment]
The directions in the README aren't the best either. "How do I create a GitHub Repo?" (this can also just be a direct link to a repo creation page in GitHub since we know the repo name and such)

**Comment by JacksonMaxfield** [comment]
README directions should include to follow the "…or push an existing repository from the command line"

**Comment by mattyweb** [comment]
Some questions as I ran through this:
1. Python version info?
2. Virtual environment instructions?
3. "municipality [Example]:" language is a little weird. Could this be something like: "Enter a municipality name:"
4. The "a CDP instance" that shows up in the generated README is confusing
5. Might want a different repo name (mine ended up being 'los-angeles') like cdr-municipality name
6. Could use some better language around the GitHub pages part

**Comment by JacksonMaxfield** [comment]
Seconding the GitHub Pages documentation. Should say something about "scroll down to 'GitHub Pages' in settings, from the 'source branch' dropdown, select the 'gh-pages' branch, and the 'root' directory, and finally click save."

**Comment by JacksonMaxfield** [comment]
Use the cookiecutter generated python project name in the build main CI. !! Initial build failure off the bat.

**Comment by JacksonMaxfield** [comment]
Pulumi and Google Cloud setup isn't explained at _all_. Just says to create those credentials but doesn't explain how.

**Comment by isometimescode** [comment]
The first step in the `Initial Repo Setup` section of the generated README says `Create a GitHub repo under the 'CouncilDataProject' account called 'anytown'`. However, it doesn't tell me where to do that (and I wouldn't have permissions to do if I'm not a part of the GH organization?)

**Comment by JacksonMaxfield** [comment]
Note to just me: the CDP github organization's secrets are causing conflicts with new deployments because the default secrets for the org are for `cdp-example`, migrate `cdp-example` secrets to be _per-repo_ instead of across the whole org. Will make for a more intuitive error.

**Comment by JacksonMaxfield** [comment]
There should be an extra bit of documentation about "creating a GitHub issue to add this new deployment to the CDP org website's list of deployments" or suggesting a pull request.

**Comment by isometimescode** [comment]
Add a link to the code where you update `get_events` and provide some code comments and links to examples on what that code needs to look like. Is there unit testing for this function?

**Comment by JacksonMaxfield** [comment]
Briefly answering this @isometimescode:

> Is there unit testing for this function?

Sorta kinda? there are lint, format, and type checks, and the pipeline will instantly try to run itself.

The only real unit test we could do for the user is checking that the type returned from the function is a `List[EventIngestionModel]`

**Comment by mattyweb** [comment]
http://santamonicacityca.iqm2.com/Citizens/
iqm2

https://lacity.primegov.com/public/portal

> Add a link to the code where you update `get_events` and provide some code comments and links to examples on what that code needs to look like. Is there unit testing for this function?

Think I found the code, but not sure what I'm supposed to have in there...a request to a page to scrape?

**Comment by JacksonMaxfield** [comment]
The code comments on the `get_events` function should probably link to: https://councildataproject.github.io/cdp-backend/ingestion_models.html

**Comment by mattyweb** [comment]
FYI, the systems being used down here seem to be IQM2 and PrimeGov...

Santa Monica: http://santamonicacityca.iqm2.com/Citizens/
Los Angeles: https://lacity.primegov.com/public/portal

It looks like the Santa Monica team has a scraper here: https://github.com/hackla-engage/engage-scraper/blob/master/engage_scraper/scraper_logics/santamonica_scraper_logic.py

**Comment by JacksonMaxfield** [comment]
@mattyweb @isometimescode I didn't realize how poorly defined this process way :sweat_smile:

I think after lunch I may start working on updating the documentation of all the issues we have already found above

**Comment by isometimescode** [comment]
> Sorta kinda? there are lint, format, and type checks, and the pipeline will instantly try to run itself.

@JacksonMaxfield In that case I'd probably add some info on how to verify that your `get_events` function works. This could be through running something locally with basic lint/type checks, how to see if the pipeline failed to build, and/or how to manually verify the data on the site itself.

**Comment by mattyweb** [comment]
I think it'd be a good idea to specify the requirements up front. It looks like we need to brew pulumi and have the Google Cloud SDK installed. Happy to do this, but would be good to give users a heads-up.

I'm going to be digging through that stuff and through the Ingestion Model for a bit...

**Comment by isometimescode** [comment]
I pushed the code to my own repo and received this [error](https://github.com/isometimescode/cdp-anytown/runs/2103567408?check_suite_focus=true#step:5:59) `No such file or directory: 'cdp_example_backend'`

**Comment by isometimescode** [comment]
![Broken Build Images](https://user-images.githubusercontent.com/7094373/111042526-a0ead180-83f2-11eb-900b-d5aa77ea0653.png)

I think these are broken because my Git repo is called `cdp-anytown` but my city is just called `Anytown`. I'm not sure which of the CLI values I entered is related to the Git repo name. Here is what I used:

```
municipality [Example]: Anytown
municipality_slug [anytown]: 
python_municipality_slug [anytown]: 
maintainer_full_name [Jackson Maxfield Brown]: Dev Deverson     
hosting_github_username_or_org [CouncilDataProject]: isometimescode
```

**Comment by JacksonMaxfield** [comment]
Sorry for the delay was talking to someone from another CfA brigade!

@isometimescode yep I got the same error.

> Use the cookiecutter generated python project name in the build main CI. !! Initial build failure off the bat.

Looks like I missed a spot for the cookiecutter to inject the name of the project.

**Comment by JacksonMaxfield** [comment]
That should be changes to `cdp_{{ python_municipality_slug }}_backend`

**Comment by JacksonMaxfield** [comment]
@isometimescode hmmmmmm I think that has to do with repo naming. If you drop the `cdp-` from the repo name those links _should_ work. But this is a good point of how to name things....

For deployments on the councildataproject organization we don't really want to have it as `councildataproject.github.io/cdp-seattle` but for deployments _not_ on the councildataproject organization we probably should prepend `cdp` to the name.

Will have to think about how to solve that.

**Comment by JacksonMaxfield** [comment]
Taking lunch for a bit!

**Comment by mattyweb** [comment]
> Taking lunch for a bit!

Sounds good. I've the GC SDK and Pulumi installed now. Just hanging tight here.

**Comment by JacksonMaxfield** [comment]
Back to work. Going to start patching some of these issues. If either of you wanted to hop back in the call it may be good to discuss where we are at / what some good next steps would be.

**Comment by mattyweb** [comment]
> Back to work. Going to start patching some of these issues. If either of you wanted to hop back in the call it may be good to discuss where we are at / what some good next steps would be.

will be able to hop on in 20

**Comment by isometimescode** [comment]
@JacksonMaxfield these are the abbreviated steps I came up with, though you may want to change the order of some of these things

1. Create an account and setup services on Google Cloud, which provides a place to store your municipality data
2. Create an account with Pulumi, which allows the CDP code to automatically deploy your municipality instance to Google Cloud
3. Create a GitHub repo, either in your own organization or in the Council Data Project org, which provides a place to store your municipality-specific code
4. Use the cookiecutter template, which creates a new directory of code for your municipality
5. Perform setup steps as defined in new directory's README (update tokens, add code for your data source, push to GitHub, gh-pages settings, ?)
6. Push to your municipality's GitHub repo and wait for automatic build to complete
7. Visit your new municipality instance/web page and verify the data

**Comment by JacksonMaxfield** [comment]
Add feature to dryrun the pipeline

**Comment by mattyweb** [comment]
I made a placeholder ticket:
https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/18
