### ISSUE TITLE
Switch from Pulumi to Terraform

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#21]
This is a large-ish project and involves some work on the https://github.com/CouncilDataProject/cdp-backend side of things.

1. Convert the CDPStack object from using Pulumi to using Terraform CDK
    https://github.com/hashicorp/terraform-cdk

2. This repo specifically needs to come up with a way to initialize a GCS backend, so that the main CDP stack can simply operate using that backend. See an example of GCS backend in typescript: [here](https://github.com/hashicorp/terraform-cdk/blob/main/examples/typescript/backends/gcs/main.ts#L2)

The goal of this work is to remove extra account setup and management; if we remove Pulumi in favor of Terraform, not only are we using a more "stable" / widely adopted tool, but we also can remove more "admin" work of account management in favor of simply a single tool.

Plus we (CDP) has an issue in on the Terraform google provider right now to add a firestore security rules resource, if we switch, we will get that resource faster whenever it is resolved. Until it is resolved we can use [terraform local exec](https://www.terraform.io/docs/language/resources/provisioners/local-exec.html) which Pulumi doesn't have a mirror for.

Steps to complete this issue:
* Rewrite the Pulumi code to Terraform CDK code (this should be decently easy), BUT, adopt a GCS backend for state storage in the `cdp-backend` infrastructure module
* Come up with strategy for having CI/CD on cookiecutter generated repos deploy a GCS backend, THEN deploy infra
* Come up with CI/CD workflow for synthesizing the CDK code -> terraform, then init, validate, apply (this is also easy)
* Update docs on `cdp-backend` dev deployment information

**Comment by Kavinraja-G** [comment]
I would like to contribute to this. Is there any contributor guidelines that should be followed ? Thanks :)

**Comment by JacksonMaxfield** [comment]
Hey @Kavinraja-G! Thanks for reaching out. This will require a whole lot of thinking before the bulk of the work is done unfortunately.

I _think_ the easiest solution while I still do the thinking on this is to switch over from Pulumi to Terraform Cloud: https://www.hashicorp.com/products/terraform/pricing

It's also free. It would still require an account setup but would still be furthering us towards using Terraform + `local_exec` for stuff.

So first things first:

The main "stack" for CDP is [here on cdp-backend](https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/infrastructure/cdp_stack.py)

So the contributing to solve the biggest part of this issue is actually on that repo (sorry for the confusion).

The first bit of progress would be to switch that component from using Pulumi SDK to using Terraform CDK (in Python).

The goal should be to have the same sort of functionality. Where that repo stores the configuration for the infrastructure, and then repos created by this cookiecutter _use_ the infrastructure module.

So todo:
* Fork + Clone your fork of `cdp-backend`
* Change the `infrastructure` module to use Terraform CDK rather than Pulumi
* Update the tests (I think these are super simple iirc)
* Ensure that the create "CDPStack" object can be imported into other python files i.e. `from cdp_backend.infrastructure import CDPStack`

That's a lot of info and I apologize. Diving into this specific issue basically touches a lot of pieces. :sweat_smile:

**Comment by JacksonMaxfield** [comment]
No longer required with Pulumi 3.0.
