### ISSUE TITLE
Create Generalized Legistar Scrapers

### ISSUE THREAD

**Issue by sarahjliu** [CouncilDataProject/cookiecutter-cdp-deployment#26]
## Use Case
Currently each new CDP deployment would need to create their own event scraper.

## Solution
Create a generalized Legistar scraper since Legistar is the most commonly used legislation tracking tool and reduce the work required to deploy a new CDP instance in those cities

**Comment by dphoria** [comment]
Work in progress https://github.com/CouncilDataProject/cdp-scrapers/pull/1

**Comment by JacksonMaxfield** [comment]
Marking as done because we merged #1
