### ISSUE TITLE
Add Process Special Event Workflow

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#46]
### Feature Description

_A clear and concise description of the feature you're requesting._

Ability to process a file / video entirely using GitHub Actions.

### Use Case

_Please provide a use case to help us understand your request in context._

No need to install or setup cdp-backend or other credentials, anyone with admin creds to the repo actions could trigger a job to process a file (special event, forum, debate, etc.) this would make it easy for multiple people to help add events to the system.

### Solution

_Please describe your ideal solution._

@isaacna added a script to `cdp-backend` that allows for processing a local file (debate, forum, special event, etc) and storing to infrastructure.

Add a GitHub Action that utilizes the bin script but also downloads the remote file to the local runner before hand. As @isaacna's script assumes the file is local to begin with iirc.

Similar to other scripts, for the job to be available for use it must also have a dummy "run on push" trigger just to make it available in the GitHub UI.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by JacksonMaxfield** [comment]
I would personally specifically call this "Process Special Event"

**Comment by isaacna** [comment]
@JacksonMaxfield 

What do you think of this:
- Changing the `process_local_file` script in `cdp_backend` to `process_special_event`
- Checks whether the `video_uri` provided in `event_details_file` is a URI for a local file or a URL to a remote resource. 
- If the `video_uri` is a remote resource, than we `resource_copy` it and use the new local file as the `video_uri`

This would abstract the logic of downloading a remote resource from the github actions bot, while also allowing people to run `process_special_event` on remote resources. 

Thoughts? I think it'd be more generalizable and stores more logic more on `cdp_backend`

**Comment by JacksonMaxfield** [comment]
Love it. In addition, you should make a parameter for `metadata_file` or `metadata_str` because the GH Action won't be able to accept a file but will be able to accept a string.

**Comment by isaacna** [comment]
> Love it. In addition, you should make a parameter for `metadata_file` or `metadata_str` because the GH Action won't be able to accept a file but will be able to accept a string.

I was planning on having a GH workflow_dispatch input for `event_details_json_string` to correspond with this [param](https://github.com/CouncilDataProject/cdp-backend/blob/main/cdp_backend/bin/process_local_file.py#L35-L39). Then we can just local JSON file for all the event etails (including the `video_uri`) and call `process_special_event` on it.

**Comment by JacksonMaxfield** [comment]
That makes more sense :joy:
