### ISSUE TITLE
Consider explicitly pinning cdp-backend and cdp-frontend versions

### ISSUE THREAD

**Issue by isaacna** [CouncilDataProject/cookiecutter-cdp-deployment#69]
### Feature Description

We should consider explicitly pinning the package versions for `cdp-backend` and `cdp-frontend`. 

### Use Case

I noticed that dependabot wasn't creating PR's in our deployments. I checked the [dependabot run](https://github.com/CouncilDataProject/test-deployment/network/updates/237107437), and it does detect the new package versions correctly, but doesn't generate a PR. According to [this post](https://github.com/dependabot/dependabot-core/issues/2894), it's because we use `~=` instead of explicitly pinning the version with `==`. In this case, dependabot isn't really doing anything. 

According to the following posts, explicit pinning favors reproducibility over re-usability. However, with dependabot I think that the re-usability disadvantage of explicit pinning is reduced. 
- https://blog.chrisgorgolewski.org/2017/12/to-pin-or-not-to-pin-dependencies.html 
- https://stackoverflow.com/questions/28509481/should-i-pin-my-python-dependencies-versions

I think for the vast majority of our dependencies, we can keep `~=`, but for `cdp-backend` and `cdp-frontend` we should pin them with `==` because they're pretty core to the deployment, and a bug in a version bump could propagate to all deployments when re-installing packages during each GH action run. Dependabot would then create PR's for the core package bumps.

### Solution

Add explicit pins on `cdp-backend` and `cdp-frontend`.

**Comment by isaacna** [comment]
Example dependabot PR after version pinning: https://github.com/isaacna/test-process-script/pull/1

**Comment by JacksonMaxfield** [comment]
Nice find!
