### ISSUE TITLE
Store content hash string on the session db model

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#75]
### Feature Description

_A clear and concise description of the feature you're requesting._

Currently if we want to look up the content hash for a session we need to go to through any transcript for the session, then the transcripts file ref, then do a split on "-" and take the first part of the split.

### Use Case

_Please provide a use case to help us understand your request in context._

Would make it much faster to get the audio file for a session if we stored the content hash on the session model itself.

### Solution

_Please describe your ideal solution._

Update the db model and the pipeline to store the content hash. Also write a script that updates old sessions with their session hashes using the transcript file ref to split process as described above.

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by JacksonMaxfield** [comment]
Closing as I just added this script and documentation: https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/blob/main/%7B%7B%20cookiecutter.hosting_github_repo_name%20%7D%7D/admin-docs/running-extra-scripts.md

**Comment by JacksonMaxfield** [comment]
Thanks @isaacna, looks like all the script and database changes rolled out totally fine: https://github.com/JacksonMaxfield/cdp-dev/runs/5177792637?check_suite_focus=true

**Comment by isaacna** [comment]
> Thanks @isaacna, looks like all the script and database changes rolled out totally fine: https://github.com/JacksonMaxfield/cdp-dev/runs/5177792637?check_suite_focus=true

Awesome glad to hear!
