### ISSUE TITLE
[Instance]: Portland, OR

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cookiecutter-cdp-deployment#79]
### Municipality Name

Portland

### Governing Body Type

city council

### Maintainer GitHub Name

dphoria

### Municipality Timezone

America/Los_Angeles

### Municipality Slug

portland

### Firestore Region

us-west1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JacksonMaxfield** [comment]
@dphoria will deploy tomorrow but just checking, what all is included in this scraper right now? Votes? Minutes items? (I wish we had the run-scraper bot on this repo too 😂)

**Comment by dphoria** [comment]
https://gist.github.com/dphoria/42f133917ac7f474bdfcfc319e5b5a03

Beyond the required sessions, we get data like EventMinuteItem.decision, Matter.result_status, sponsors, supporting_files, votes. We also get minutes_item but that may be same as matter at the moment.

**Comment by JacksonMaxfield** [comment]
From the above JSON dump I think everything looks correct there except that the third session is from 2/17 not 2/16.

**Comment by dphoria** [comment]
Yes that is actually an oft-observed pattern from Portland. The last session of a meeting often takes place on the second day. See https://www.portland.gov/council/agenda/all; many meetings span multiple days. I don't know why they do it this way. i.e. Why include the session from the "next" day on the same agenda?

Regardless, do you think it's better for CDP purposes, to treat that session as part of a different EventIngestionModel?

**Comment by JacksonMaxfield** [comment]
That is a perfect answer. Seems like they really do have multi-day meetings. Cool.

Who knows, but if that is what it says on the official agenda then that is what we should do as well.

Awesome. I will start the deployment process in ~1 hour

**Comment by CouncilDataProjectServiceAccount** [comment]
Deployment Status - Complete

Instance available at: http://councildataproject.org/portland/#/
Running first data gather: https://github.com/CouncilDataProject/portland/runs/5283363985?check_suite_focus=true

**Comment by JacksonMaxfield** [comment]
@dphoria looks like this is all ready to go with the exception that this PR (https://github.com/CouncilDataProject/cdp-backend/pull/169) needs to be merged into `cdp-backend` and a new patch released to allow portland to go through.

**Comment by dphoria** [comment]
Thank you Jackson! We are almost there @Shak2000!
