### ISSUE TITLE
Potentially add timezome to cookiecutter parameters

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#83]
Up for discussion, @tohuynh is moving from moment.js to our own datetime localization functions for a whole bunch of reasons, as a part of that, there is the addition of a timezone property in the website config, I propose that the timezone should simply be a cookiecutter parameter.

**Comment by tohuynh** [comment]
In the GitHub form users already enter an IANA time zone right?

**Comment by JacksonMaxfield** [comment]
Yes but that is just for the GitHub form -> attempting to generate a Legistar Scraper for them. It isn't a full cookiecutter param yet.

**Comment by tohuynh** [comment]
OK. The requirement is either an IANA time zone or "UTC".

**Comment by JacksonMaxfield** [comment]
Yep! That works for me.

**Comment by evamaxfield** [comment]
This has been done for a while :woman_shrugging:
