### ISSUE TITLE
[Instance]: Albuquerque

### ISSUE THREAD

**Issue by evamaxfield** [CouncilDataProject/cookiecutter-cdp-deployment#95]
### Municipality Name

Albuquerque

### Governing Body Type

city council

### Maintainer GitHub Name

evamaxfield

### Legistar Client Id

cabq

### Municipality Timezone

America/Denver

### Municipality Slug

albuquerque

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

_rerunning_

**Comment by JacksonMaxfield** [comment]
Going to restart and use a specific infra slug. I think this infra slug may be too long.

**Comment by JacksonMaxfield** [comment]
Can't deploy things right now likely due to Pulumi errors.

**Comment by evamaxfield** [comment]
Deployment Status - Complete

GitHub: https://github.com/CouncilDataProject/albuquerque
Website: https://councildataproject.org/albuquerque/#/
Initial Backfill: https://github.com/CouncilDataProject/albuquerque/runs/7989205487?check_suite_focus=true
